language: node_js
node_js: node
addons:
  chrome: stable
before_install:
- curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASS} https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/attest/auth/attest
  > .npmrc
- npm install attest --registry=https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/attest/
install:
- npm install
before_script:
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
env:
  global:
  - SAUCE_USERNAME: Desire2Learn
  - secure: g6pGTCYE7QO+lVinZyDGeCRm2ghnhasuB4xUYsv58pXHy7cJWX/S/xc9A9kgfzeuk5Pc860JcfgJkPIwmJfJ3BlLob2OINNCXDMSdeC8hTmvTkXLHNjapxlxHDJDgEH644RTnRMt1/F7Ffh2t+wpdY1AwHRFkjuUhKSC2/GHUtfa43RpsQyQSw9oaLWaTM1l+HU4Rk2oYKSFGSqSdbfnQ997tNDvfCDS06ZvgrwtJMC8pWjKZos4tQeOtFUxFzNqoA713GZQj5KAnoOtIl7tm+cX0srKktBm35pduOiHeQYj7fBze6hi4V0xYl0mD019FbzALF8s/yWUOsZTPe6EkhOQWK8/BRFG2e/RtGAd/HWHj7j51xjFunP9d6x0pWXpMINQe6KWvdNoNAQrs3lS2+aJ2ERFvJ36nSRsd/e/QCg8pS3IZO4oKRJ2VNSZpIRlb1/j3KeJ1gyL8XulV3tOpQOapLtmXI4o3oKXjn7FFGmEcK/R08A3O6sKkSTad9yST9JRg8w0XHxOM4ld6HQ/O6SazAfgwDV39Tvpq+ACh5mfhcL42bO81ezFfsxwgUckm91KMNDVqGe3zbGnzOXGDir2dS6c348CgkJBO67wYiut8kWkL70VxFh8K/ugnW2zqVWgMoWSsApffADl+FGyCfOceFLN70romEshcL1whj8=
